name: Deploy Gmae
on:
  push: 
     branches: [main] 
jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v5
        with:
           go-version: '1.21'
      - name: Build WebAssembly
        run: |
          GOOS=js GOARCH=wasm go build -o ui/arrows.wasm .
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-peges
          
